name: devops-test
services:
  app:
    build: ./app
    env_file: .env
    restart: unless-stopped
    networks: [web]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  nginx:
    build: ./nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - nginx_logs:/var/log/nginx
    restart: unless-stopped
    networks: [web]

volumes:
  nginx_logs:

networks:
  web:
    driver: bridge
