name: devops-test
services:
  app:
    container_name: hello_world_container
    build: ./app
    env_file: .env
    restart: unless-stopped
    networks: [web]

  nginx:
    container_name: nginx_container
    build: ./nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - nginx_logs:/var/log/nginx
    restart: unless-stopped
    networks: [web]

volumes:
  nginx_logs:

networks:
  web:
    driver: bridge
    ##
